import React from "react";
import Head from "next/head";
import styles from "./Layout.module.css";

const Layout = () => {
  return (
    <div>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=ABeeZee&family=Questrial&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://use.fontawesome.com/releases/v6.2.0/css/all.css"
          rel="stylesheet"
        />
      </Head>
    </div>
  );
};
export default Layout;
