import React from "react";
import Head from "next/head";

const Layout = () => {
  return (
    <div>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>❄️</text></svg>"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=ABeeZee&family=Questrial&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://use.fontawesome.com/releases/v6.2.0/css/all.css"
          rel="stylesheet"
        />
      </Head>
    </div>
  );
};
export default Layout;
