import React from "react";
import Head from "next/head";

const Layout = () => {
  return (
    <div>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icons8-snowflake-48.png" type="image/png" />
      </Head>
    </div>
  );
};
export default Layout;
