import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.maincontainer}>
      <Head>
      <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=ABeeZee&family=Questrial&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://use.fontawesome.com/releases/v6.2.0/css/all.css"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.subcontainer}>
        <nav className={styles.nav}>
          <ul className={styles.navul}>
            <li className={styles.navli}>
              <a className={styles.nava} href="/">
                Home
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="/about">
                About
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="/projects">
                Projects
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="articles">
                Articles
              </a>
            </li>
            <li className={styles.navli}>
              <div className={styles.navicon}>
                <a href="https://github.com/yuki-o1o5" target="_blank">
                  <i class="fa-brands fa-square-github fa-2x fa-fw"></i>
                </a>
                <a
                  href="https://www.linkedin.com/in/yuki-kasugai-136826247/"
                  target="_blank"
                >
                  <i class="fa-brands fa-linkedin fa-2x fa-fw"></i>
                </a>
                <a href="mailto:sample@sample.com">
                  <i class="fa-solid fa-square-envelope fa-2x fa-fw"></i>
                </a>
                <a href="#" target="_blank">
                  <i class="fa-solid fa-square-poll-horizontal  fa-2x fa-fw"></i>
                </a>
              </div>
            </li>
          </ul>
        </nav>

        <main className={styles.main}>
          <section className={styles.aboutme}>
            <h2 className={styles.titleh2}>About Me</h2>
            <p className={styles.namepcommon}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Vestibulum rhoncus est pellentesque elit ullamcorper dignissim
              cras tincidunt. In hac habitasse platea dictumst. Massa enim nec
              dui nunc mattis enim ut tellus. Donec ultrices tincidunt arcu non
              sodales neque sodales. Placerat in egestas erat imperdiet sed
              euismod nisi porta lorem. Aliquam id diam maecenas ultricies mi
              eget mauris pharetra.
            </p>
          </section>
          <section className={styles.techstack}>
            <h2 className={styles.titleh2}>Tech Stack</h2>
              <div className={styles.techstackparent}>
                  <img className={styles.techstackimg} src="../assets/html.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/css.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/javascript.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/react.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/nextjs.png" alt=""></img>
              </div>
          </section>
        </main>
      </div>
    </div>
  );
}
