import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.subcontainer}>
        <nav>
          <ul>
            <li className={styles.navli}>
              <a href="#">Home</a>
            </li>
            <li className={styles.navli}>
              <a href="#">About</a>
            </li>
            <li className={styles.navli}>
              <a href="#">Projects</a>
            </li>
            <li className={styles.navli}>
              <a href="#">Articles</a>
            </li>
            <li className={styles.navli}>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
            </li>
          </ul>
        </nav>

        <main className={styles.main}>
          <section className={styles.aboutme}>
            <h2 className={styles.titleh2}>About Me</h2>
            <p className={styles.namepcommon}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
              Vestibulum rhoncus est pellentesque elit ullamcorper dignissim
              cras tincidunt. In hac habitasse platea dictumst. Massa enim nec
              dui nunc mattis enim ut tellus. Donec ultrices tincidunt arcu non
              sodales neque sodales. Placerat in egestas erat imperdiet sed
              euismod nisi porta lorem. Aliquam id diam maecenas ultricies mi
              eget mauris pharetra.
            </p>
          </section>
          <section className={styles.techstack}>
            <h2 className={styles.titleh2}>Tech Stack</h2>
              <div className={styles.techstackparent}>
                  <img className={styles.techstackimg} src="../assets/html.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/css.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/javascript.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/react.png" alt=""></img>
                  <img className={styles.techstackimg}  src="../assets/nextjs.png" alt=""></img>
              </div>
          </section>
        </main>
      </div>
    </div>
  );
}
