import Head from "next/head";
import styles from "../styles/Home.module.css";

const articles = () => {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.subcontainer}>
        <nav>
          <ul>
            <li className={styles.navli}>
              <a href="#">Home</a>
            </li>
            <li className={styles.navli}>
              <a href="#">About</a>
            </li>
            <li className={styles.navli}>
              <a href="#">Projects</a>
            </li>
            <li className={styles.navli}>
              <a href="#">Articles</a>
            </li>
            <li className={styles.navli}>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
            </li>
          </ul>
        </nav>

      <main className={styles.main}>
        <div>
          <h2>My Articles</h2>
          <div>
            <div>
              <h3>Article title</h3>
              <p>@div.to</p>
            </div>
          </div>
        </div>
      </main>
      </div>
    </div>
  );
};

export default articles;
