import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=ABeeZee&family=Questrial&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://use.fontawesome.com/releases/v6.2.0/css/all.css"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.subcontainer}>
        <nav className={styles.nav}>
          <ul className={styles.navul}>
            <li className={styles.navli}>
              <a className={styles.nava} href="/">
                Home
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="/about">
                About
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="/projects">
                Projects
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="articles">
                Articles
              </a>
            </li>
            <li className={styles.navli}>
              <div className={styles.navicon}>
                <a href="https://github.com/yuki-o1o5" target="_blank">
                  <i class="fa-brands fa-square-github fa-2x fa-fw"></i>
                </a>
                <a
                  href="https://www.linkedin.com/in/yuki-kasugai-136826247/"
                  target="_blank"
                >
                  <i class="fa-brands fa-linkedin fa-2x fa-fw"></i>
                </a>
                <a href="mailto:sample@sample.com">
                  <i class="fa-solid fa-square-envelope fa-2x fa-fw"></i>
                </a>
                <a href="#" target="_blank">
                  <i class="fa-solid fa-square-poll-horizontal  fa-2x fa-fw"></i>
                </a>
              </div>
            </li>
          </ul>
        </nav>

        <main className={styles.main}>
          <div className={styles.namecontainer}>
            <section>
              <h1 className={styles.nameh1}>Yuki Kasugai</h1>
              <p className={styles.namep1}>
                I'm a Front-End Developer in Vancouver!
              </p>
            </section>
            <img
              className={styles.nameimg}
              src="../assets/yukikasugai.jpg"
              alt="yukikasugai"
            ></img>
          </div>
          <p className={styles.namepcommon}>
            Lorem ipsum dolor sit amet, consectetur elit adipiscing, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Faucibus
            ornare suspendisse sed nlacus.
          </p>
        </main>
      </div>
    </div>
  );
}
