import Head from "next/head";
import styles from "../styles/Home.module.css";

const projects = () => {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.subcontainer}>
        <nav>
          <ul>
            <li className={styles.navli}>
              <a href="#">
                Home
              </a>
            </li>
            <li className={styles.navli}>
              <a href="#">About</a>
            </li>
            <li className={styles.navli}>
              <a href="#">Projects</a>
            </li>
            <li className={styles.navli}>
              <a href="#">Articles</a>
            </li>
            <li className={styles.navli}>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
              <a href="#">
                <img src="" alt=""></img>
              </a>
            </li>
          </ul>
        </nav>

        <main className={styles.main}>
          <div>
            <h2>My Projects</h2>
            <div>
              <img src="#" alt="#"></img>
              <section>
                <h3>Web site title</h3>
                <div>
                  <p>#React #HTML #CSS #JavaScript</p>
                  <div>
                    <a href="#">
                      <img src="#" alt="#"></img>
                    </a>
                    <p>GitHub</p>
                  </div>
                </div>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  A diam sollicitudin tempor id eu nisl.
                </p>
              </section>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default projects;
