import Head from "next/head";
import styles from "../styles/Home.module.css";

const projects = () => {
  return (
    <div className={styles.maincontainer}>
      <Head>
      <title>Yuki | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=ABeeZee&family=Questrial&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://use.fontawesome.com/releases/v6.2.0/css/all.css"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.subcontainer}>
        <nav className={styles.nav}>
          <ul className={styles.navul}>
            <li className={styles.navli}>
              <a className={styles.nava} href="/">
                Home
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="/about">
                About
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="/projects">
                Projects
              </a>
            </li>
            <li className={styles.navli}>
              <a className={styles.nava} href="articles">
                Articles
              </a>
            </li>
            <li className={styles.navli}>
              <div className={styles.navicon}>
                <a href="https://github.com/yuki-o1o5" target="_blank">
                  <i class="fa-brands fa-square-github fa-2x fa-fw"></i>
                </a>
                <a
                  href="https://www.linkedin.com/in/yuki-kasugai-136826247/"
                  target="_blank"
                >
                  <i class="fa-brands fa-linkedin fa-2x fa-fw"></i>
                </a>
                <a href="mailto:sample@sample.com">
                  <i class="fa-solid fa-square-envelope fa-2x fa-fw"></i>
                </a>
                <a href="#" target="_blank">
                  <i class="fa-solid fa-square-poll-horizontal  fa-2x fa-fw"></i>
                </a>
              </div>
            </li>
          </ul>
        </nav>

        <main className={styles.main}>
          <div>
            <h2 className={styles.titleh2}>My Projects</h2>
            <div className={styles.projects}>
              <img
                className={styles.projectsimg}
                src="../assets/main3.jpeg#"
                alt="#"
              ></img>
              <section className={styles.textsection}>
                <h3 className={styles.subtitleh3}>Web site title</h3>
                <div className={styles.projectscontainer1}>
                  <p className={styles.projectslink}>#React #HTML #CSS #JavaScript</p>
                  <div className={styles.projectscontainer2}>
                    <a href="#">
                      <i class="fa-brands fa-square-github  fa-lg fa-fw"></i>
                    </a>
                    <p className={styles.projectslink}>GitHub</p>
                  </div>
                </div>
                <p className={styles.projectsp}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  A diam sollicitudin tempor id eu nisl.
                </p>
              </section>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default projects;
