import React from "react";
import Image from "next/image";
import styles from "./Techstack.module.css";

const Teckstack = () => {
  return (
    <section className={styles.techstack_container}>
      <h2 className={styles.techstack_title}>Tech Stack</h2>
      <div className={styles.techstack_img_container}>
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
          alt="html5"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
          alt="css3"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
          alt="Sass"
          width="50"
          height="50"
        />
        <Image
          src="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
          alt="tailwind"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
          alt="Bootstrap"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
          alt="Javascript"
          width="50"
          height="50"
        />
        <Image
          src="/assets/ts-logo-128.png"
          alt="Typescript"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
          alt="react"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
          alt="redux"
          width="50"
          height="50"
        />
        <Image
          src="/assets/nextjs-icon-dark-background.png"
          alt="Next.js"
          width="50"
          height="50"
        />
        <Image
          src="/assets/vercel-icon-dark.png"
          alt="Vercel"
          width="50"
          height="50"
        />
        <Image
          src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
          alt="sqlite"
          width="50"
          height="50"
        />
        <Image
          src="https://www.mysql.com/common/logos/logo-mysql-170x115.png"
          alt="MySQL"
          width="50"
          height="50"
        />
        <Image
          src="https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg"
          alt="postgresql"
          width="50"
          height="50"
        />
        <Image
          src="/assets/supabase-logo-icon.png"
          alt="Vercel"
          width="50"
          height="50"
        />
        <Image
          src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
          alt="Figma"
          width="50"
          height="50"
        />
      </div>
    </section>
  );
};
export default Teckstack;
